In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm # Estadísticas R Adjused
import seaborn as sns  # Gráficos
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures # Polinomial

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
datos = pd.read_csv("https://raw.githubusercontent.com/rpizarrog/Analisis-Inteligente-de-datos/main/datos/Advertising_Web.csv")
datos

     Unnamed: 0    X     TV  Radio  Newspaper         Web  Sales
0             1    1  230.1   37.8       69.2  306.634752   22.1
1             2    2   44.5   39.3       45.1  302.653070   10.4
2             3    3   17.2   45.9       69.3   49.498908    9.3
3             4    4  151.5   41.3       58.5  257.816893   18.5
4             5    5  180.8   10.8       58.4  195.660076   12.9
..          ...  ...    ...    ...        ...         ...    ...
195         196  196   38.2    3.7       13.8  248.841073    7.6
196         197  197   94.2    4.9        8.1  118.041856    9.7
197         198  198  177.0    9.3        6.4  213.274671   12.8
198         199  199  283.6   42.0       66.2  237.498063   25.5
199         200  200  232.1    8.6        8.7  151.990733   13.4

[200 rows x 7 columns]

In [3]:
datos[['TV','Radio', 'Newspaper', 'Web', 'Sales', ]].describe()

               TV       Radio   Newspaper         Web       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000  159.587355   14.022500
std     85.854236   14.846809   21.778621   76.815266    5.217457
min      0.700000    0.000000    0.300000    4.308085    1.600000
25%     74.375000    9.975000   12.750000   99.048767   10.375000
50%    149.750000   22.900000   25.750000  156.862154   12.900000
75%    218.825000   36.525000   45.100000  212.311848   17.400000
max    296.400000   49.600000  114.000000  358.247042   27.000000

Limpiar datos

In [5]:
X_independientes = datos.iloc[:,2:6]
X_independientes

        TV  Radio  Newspaper         Web
0    230.1   37.8       69.2  306.634752
1     44.5   39.3       45.1  302.653070
2     17.2   45.9       69.3   49.498908
3    151.5   41.3       58.5  257.816893
4    180.8   10.8       58.4  195.660076
..     ...    ...        ...         ...
195   38.2    3.7       13.8  248.841073
196   94.2    4.9        8.1  118.041856
197  177.0    9.3        6.4  213.274671
198  283.6   42.0       66.2  237.498063
199  232.1    8.6        8.7  151.990733

[200 rows x 4 columns]

In [6]:
Y_dependiente = datos.iloc[:, 6:7]
Y_dependiente

     Sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
..     ...
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]

Datos de entrenamiento y datos de validación

In [7]:
X_entrena,X_valida,Y_entrena,Y_valida = train_test_split(X_independientes, Y_dependiente,train_size=.70,  random_state=1280)

Modelo de Regresión lineal múltiple

In [8]:
modelo_rm = LinearRegression()
 
modelo_rm.fit(X_entrena,Y_entrena)

LinearRegression()

Predicciones

In [9]:
predicciones = modelo_rm.predict(X_valida)
print(predicciones[:-1])

[[ 9.55723431]
 [12.22096155]
 [18.75777207]
 [17.74093239]
 [22.67903345]
 [13.23346367]
 [11.58367739]
 [22.7844508 ]
 [10.62122293]
 [14.77458399]
 [20.94992544]
 [ 8.24858906]
 [11.95793495]
 [13.94551018]
 [20.75351685]
 [17.1563593 ]
 [19.29232912]
 [19.15642422]
 [19.44242535]
 [21.21665167]
 [ 7.5524368 ]
 [23.30141628]
 [14.94766425]
 [20.05523426]
 [ 5.05880741]
 [ 9.44816783]
 [17.11356987]
 [12.28246619]
 [20.69413996]
 [ 6.26821687]
 [14.15794284]
 [15.12820418]
 [13.60742097]
 [12.70617782]
 [19.72037125]
 [16.71849409]
 [ 8.11050021]
 [23.08575043]
 [21.43804181]
 [13.69342166]
 [13.77165263]
 [17.27021586]
 [10.69785161]
 [17.06691391]
 [15.73054687]
 [ 6.69859652]
 [21.84767203]
 [10.07156777]
 [14.37706798]
 [13.96959623]
 [10.05622915]
 [14.42757802]
 [11.95725093]
 [18.24664493]
 [ 8.52085517]
 [21.1916941 ]
 [12.17401015]
 [18.07041045]
 [20.66284756]]