In [1]:
import pandas as pd
df = pd.read_csv("carprices.csv")
df.head()

   Mileage  Age(yrs)  Sell Price($)
0    69000         6          18000
1    35000         3          34000
2    57000         5          26100
3    22500         2          40000
4    46000         4          31500

In [2]:
X = df[['Mileage','Age(yrs)']]
y = df[['Sell Price($)']]

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

X_train

    Mileage  Age(yrs)
16    28000         2
14    82450         7
9     67000         6
15    25400         3
1     35000         3
5     59000         5
7     72000         6
19    52000         5
13    58780         4
17    69000         5
3     22500         2
8     91000         8
11    79000         7
0     69000         6

In [4]:
from sklearn.linear_model import LinearRegression
clf= LinearRegression()
clf.fit(X_train, y_train)

LinearRegression()

In [5]:
clf.predict(X_test)

array([[27211.77152341],
       [14341.49559398],
       [25096.43849958],
       [16435.67043144],
       [25700.81936353],
       [29729.01296563]])

In [6]:
y_test

    Sell Price($)
6           32000
18          12800
12          26000
10          18700
2           26100
4           31500

In [7]:
clf.score(X_test, y_test)

0.8768919140846522